title: Notes
description: Notes from the UW
theme: just-the-docs
author: Carter Swartout

url: https://cswartout.com/notes
# favicon_ico: "/assets/images/favicon.ico" # TODO

color_scheme: dark

# LaTeX rendering via "katex" (KaTeX, default) or "mathjax" (MathJax) or "none" / "off" (NO rendering)
latex: katex
compress_html:
    blanklines: true

aux_links:
    "Carter's Website":
        - "//cswartout.com"