title: Notes
description: Notes from the UW
theme: just-the-docs
author: Carter Swartout

url: https://cswartout.com
baseurl: /notes

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
